### ISSUE TITLE
[0.2.25] NoMethodError undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by bartoszkopinski** [boazsegev/combine_pdf#74]
I'm getting this error after upgrading from 0.2.23 to 0.2.25. 

This is the backtrace:
```
NoMethodError undefined method `+' for nil:NilClass
vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.25/lib/combine_pdf/pdf_protected.rb:299:in `merge_outlines': undefined method `+' for nil:NilClass (NoMethodError)
from vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.25/lib/combine_pdf/pdf_public.rb:302:in `insert'
from vendor/bundle/ruby/2.3.0/gems/combine_pdf-0.2.25/lib/combine_pdf/pdf_public.rb:274:in `<<'
```

Code:
```ruby
pdf = uploader.retrieve_file_content(s3_filename)
pdf_files[key] ||= CombinePDF.new
pdf_files[key] << CombinePDF.parse(pdf) # Exception
```

Let me know if you need more details.

**Comment by boazsegev** [comment]
Hi Bartosz,

Thank you for opening this issue.

I think the issue might have been fixed in version 0.2.27.... could you review?

(we had a few busy days rewriting some of the core algorithms to minimize recursion and rolling out the outline merging feature).

If the issue persists, could you share with me an example file. The library is working on all the test files I've got. Reviewing the file will both help me track down the cause and test future versions.

Thanks!
Bo.

**Comment by bartoszkopinski** [comment]
@boazsegev Thanks for the reply. 
You're right, it looks like it's been fixed. I didn't notice the latest version, sorry.

**Comment by bartoszkopinski** [comment]
BTW. If you want, you can mark any broken versions as "yanked" in rubygems: http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem#tutorial

**Comment by boazsegev** [comment]
Thanks for the tip. I marked it as "yanked", however I must admit I usually avoid this (all teeny versions are bug fixes and non API breaking updates, by this logic, all teeny updates require yanking the previous teeny version)... however, you're right, it's been a busy week :-)
