### ISSUE TITLE
undefined method `[]' for nil:NilClass error on windows

### ISSUE THREAD

**Issue by espinosa** [boazsegev/combine_pdf#16]
<code>
CombinePDF.new('mypdf.pdf')
</code>
.../Ruby200/lib/ruby/gems/2.0.0/gems/combine_pdf-0.1.18/lib/combine_pdf/
combine_pdf_parser.rb:163:in `_parse_': undefined method `[]' for nil:NilClass (
NoMethodError)

*Ruby 2.0.0p481 / Win7 / Version 0.1.18*

Work fine on ruby 2.2.0p0@debian

Try to give you more debug info later.

**Comment by boazsegev** [comment]
Thank you Espinosa for opening this issue.

I don't have a Win7 VM, so it might be hard for me to test the issue... also, I have a midterm coming up in two days, so I'm somewhat busy. This one might take me some time, both to trace and to fix, and I'm sorry for any inconvenience.

I wonder if the issue is related to a specific PDF file or an issue caused by a wrong installation... let me explain why:

1.  [The code on line 163](https://github.com/boazsegev/combine_pdf/blob/e1cd33179eec3af8690a6ca90e7867cb47e8f71d/lib/combine_pdf/combine_pdf_parser.rb#L163) is related to error control and is supposed to log an error and raise an exception... Hence, it might be a specific PDF file. BUT...

2. ...the original code and the line trace don't match. The original code doesn't call #[] on any object, since the original code runs: `warn "Stream not attached to dictionary!"` ... So, maybe, something was wrong with the gem installation... could you try uninstalling and reinstalling the gem?

**Comment by espinosa** [comment]
Thanks for your quickly response, boazsegev.
Sorry, it was line 160 on original code (added few lines for debug purpose):
<code>
out.last[:raw_stream_content] = **str**[0...-10] 
</code>
**str is null**

I will dump @scanner and compare with linux env later.

**Comment by boazsegev** [comment]
I added some code to refine the parsing EOL markers for stream objects (beginning on line 156). Could you review and let me know what changed? Notice that exceptions thrown might catch the bug without fixing it...

**Comment by espinosa** [comment]
The exception is raised.
Which variables of StringScanner can I debug to compare with linux env ?

**Comment by boazsegev** [comment]
Here are a few thoughts about information to to look for, that might help track down the issue (Is it just me or is it's starting to look like a ruby bug which we should work around?):

- `@scanner.matched?` (should be `true`, is probably `false`)
- `@scanner.matched` (should be `"...stream data... \nendstream"`, is probably `nil`)
- `@scanner.pos`x2 (does it change before and after the `str = @scanner.scan_until(/(\r\n|\r|\n)endstream/)` ?)
- `@scanner.post_match` (return the data operated upon - check before and after `@scanner.scan_until` is called)

I think this should be a great start to review when happened. Did it scan successfully without assigning the resulted str? did in to scan? why didn't it find the info? ...

**Comment by espinosa** [comment]
Here is the debug:
# ruby 2.2.0p0 on debian
## 0.1.18:
    @scanner.matched? = true
    @scanner.matched = stream
    @scanner.pos (before) = 68
	@scanner.pos (after) = 11630

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 11714
	@scanner.pos (after) = 21885

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 22643
	@scanner.pos (after) = 44804

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 44901
	@scanner.pos (after) = 61559

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 61656
	@scanner.pos (after) = 68480

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 68576
	@scanner.pos (after) = 80730
## fix  24f77fa :
	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 68
	@scanner.pos (after) = 44804

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 44901
	@scanner.pos (after) = 61559

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 61656
	@scanner.pos (after) = 68480

	@scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 68576
	@scanner.pos (after) = 80730

**didn't find reference {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>1}
Couldn't connect all values from references - didn't find reference {:Size=>35, :Root=>nil, :Info=>{:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>2}, :ID=>["\xF5\xA6CE,\x8ER\xA9\x15\xDC#\xD7ll\xC0\x1C", "\xF5\xA6CE,\x8ER\xA9\x15\xDC#\xD7ll\xC0\x1C"]}!!!
couldn't connect a reference!!! could be a null or removed (empty) object, Silent error!!!
 Object raising issue: {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>6, :referenced_object=>nil}
couldn't connect a reference!!! could be a null or removed (empty) object, Silent error!!!
 Object raising issue: {:is_reference_only=>true, :indirect_generation_number=>0, :indirect_reference_id=>23, :referenced_object=>nil}**

# ruby 2.0.0p481 on Win7

## 0.1.18 & fix 24f77fa :
    @scanner.matched? = true
	@scanner.matched = stream
	@scanner.pos (before) = 68
	@scanner.pos (after) = 68
**Parsing Error: PDF file error - a stream object wasn't properly colsed using 'endstream'! (RuntimeError)**

The problem is on *@scanner.pos (after) = 68* instead of *@scanner.pos (after) = 11630* .
StringScanner#scan_util doesn't change the pos ?!

**Comment by espinosa** [comment]
# @scanner.pre_match
## debian
    %PDF-1.4
    %Çì¢
    5 0 obj
    <</Length 6 0 R/Filter /FlateDecode>>
## win7
    %PDF-1.4
    %����
    5 0 obj
    <</Length 6 0 R/Filter /FlateDecode>>

Seems to be an encoding problem on windows...

**Comment by boazsegev** [comment]
Wow, nice catch! I'm not sure I would have found the glitch there... Thanks!

I'll merge the pull request, just before I do:

I noticed you reverted the new regular expressions to the old ones. I'm referring to the code at line 156:
```
				when @scanner.scan(/stream(\r\n|\r|\n)/)
					str = @scanner.scan_until(/(\r\n|\r|\n)endstream/)
```

I'm wondering if the new regular expressions caused issues? I think they are closer to the ISO then the original code and I would rather keep them if they work... but I didn't have time to properly test them out.

**Comment by espinosa** [comment]
Thé new regexp caused **didn't find référence** warning.
You can sée full message on my previous message under fix 24f77fa:

**Comment by boazsegev** [comment]
Yes, it seems as if the new Regex took the first three streams together on your PDF and collected them as if they were one object. After that, it works as expected...

I wonder why that happened. I know that the parser shouldn't be too strict while adhering to the standards, but I'm not sure if ignoring the required EOL markers might not cause issues with stream objects that have uncompressed text containing the key word 'endstream' of some reason...

Would it be possible for me to check the specific PDF file you used? I tested a large number of files on my machine and there weren't any issues.

**Comment by boazsegev** [comment]
Nevermind, I found a PDF file that doesn't conform to the PDF standard and has an EOF marker instead of an EOL marker... It seems they are more common the comforting PDF files which contain the 'endstream' keyword as a legitimate part of the PDF object stream....

I released an updated version (v.0.1.20) with the non-strict parser RegExp.

Again, THANK YOU very much for helping make the combine_pdf gem even better! 🙏
